# Generated by Django 2.2.3 on 2019-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exammanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocate',
            name='seatno',
            field=models.CharField(max_length=10),
        ),
    ]
