# Generated by Django 2.2.3 on 2019-09-18 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exammanager', '0002_auto_20190916_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
