# Generated by Django 2.2.3 on 2019-09-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exammanager', '0003_addstudent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocate',
            name='roll',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
